# Site settings
title: for the cLove of Garlic
email: dtphelan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's a food blog. The wonderful Meagan Phelan brings you delicious recipies,
  patented RD Rants, and anything else that comes to mind. Eat up!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://forthecloveofgarlic.github.io" # the base hostname & protocol for your site
twitter_username: RDMegD
github_username:  forthecloveofgarlic

# Build settings
markdown: kramdown

paginate: 4

author: Meagan Phelan

gems: [jekyll-paginate]

permalink: /:categories/:title/
