# Site settings
title: RD Eating
email: rdeating@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to RD Eating! My name is Meagan, and I'm a Registered Dietitian living in Washington, DC. On this site, you'll find a variety of recipes and nutrition information that I hope will inspire you to make delicious, nutritious meals at home!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rdeating.com" # the base hostname & protocol for your site
twitter_username: RDMegD
github_username:  RDEating
pinterest_username: meagan6518
instagram_username: meagan.phelan

# Build settings
markdown: kramdown

paginate: 4

author: Meagan Phelan

gems: [jekyll-paginate]

permalink: /:categories/:title/

prose:
  ignore:
    - .gitignore
    - _config_dev.yml
    - _config.yml
    - /_includes
    - /_layouts
    - /_sass
    - /_site
    - CNAME
    - /css
    - feed.xml
    - /fonts
    - index.html
    - /js
    - LICENSE
    - README.md
  media: "images"
  metadata:
    - name: "title"
      field:
        element: "text"
        label: "title"
    - name: "subheadline"
      field:
        element: "text"
        placeholder: "Subheadline"
    - name: "date"
      field:
        element: "text"
        placeholder: "Date, in YEAR-MONTH-DAY format, i.e., 2015-04-02"
    - name: "categories"
      field:
        element: "multiselect"
        label: "Add Categories"
        options:
          - name: "Recipes"
            value: "recipies"
          - name: "Dinner"
            value: "dinner"
